#! /bin/sh

# ┌─┐┬  ┌─┐┬ ┬┌─┐┌┬┐┌─┐┬ ┬
# ├┤ │  │ ││││├┤  │ │  ├─┤
# └  ┴─┘└─┘└┴┘└─┘ ┴ └─┘┴ ┴

# Get packages
pkg="$(brew list | wc -l | tr -d ' ')"

# Get user
user="${USER-$(id -u -n)}"

# Get host
host=$(uname -n | sed 's/\.local//')

# Get OS
os="$OSTYPE"

# Get uptime
up="$(echo "scale=0; ($(date +%s) - $(sysctl -n kern.boottime | awk '{print $4}' | tr -d ',')) / 3600" | bc)h"

# Shell
shell="${SHELL##*/}"

# Desktop Environment
de="aqua"

# Colors

c0='[0m'
c1='[31m'
c2='[32m'
c3='[33m'
c4='[34m'
c5='[35m'
c6='[36m'
c7='[37m'
c8='[38m'
c9='^[[37m'

# Art

ARTR1="${c1}     _ _    "
ARTR2="${c1}    (_\_)   "
ARTR3="${c1}   (__<__)  "
ARTR4="${c1}    (_/_)   "
ARTR5="${c2}    \ |     "
ARTR6="${c2}     \|/    "

# Main Print

cat <<-EOF

 ${ARTR1}  ${c5}host${c0}    ${c1}•••   ${host}
 ${ARTR2}  ${c5}user${c0}    ${c2}•••   ${user}
 ${ARTR3}  ${c5}shell${c0}   ${c3}•••   ${shell}
 ${ARTR4}  ${c5}de${c0}      ${c4}•••   ${de}
 ${ARTR5}  ${c5}up${c0}      ${c5}•••   ${up}
 ${ARTR6}  ${c5}pkg${c0}     ${c6}•••   ${pkg}

EOF
